# Configuration for Black.

# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.

[tool.black]
line-length = 79
target-version = ['py39']
extend-exclude = '''
/(
    \.git
  | \.toml
  | \.hg
  | \.eggs
  | \__pycache__
  | \.tox
  | \.nox
  | \.venv
  | \.csv
  | \.txt
  | \.rst
  | \.parquet
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.semantic_release]
version_variable = 'setup.py:__version__'
branch = 'main'
upload_to_release = true
upload_to_repository = false

# pyproject.toml
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests"
]